
- name: configure kubernetes node hostnames
  hosts: k8s_cluster
  become: true

  tasks:

    - name: set hostnames based on inventory name
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"

    - name: configure /etc/hosts for kubernetes nodes
      ansible.builtin.blockinfile:
        path: /etc/hosts
        marker: "# {mark} ANSIBLE MANAGED K8S HOSTS"
        block: |
          {{ cp1_ip }} k8slab-cp1
          {{ w1_ip }} k8slab-w1

    
    - name: disable swap immediately
      ansible.builtin.command:
        cmd: swapoff -a
      when: ansible_swaptotal_mb > 0                   # Only run swapoff -a if this machine actually has active swap.

    - name: disable swap permanently in /etc/fstab
      ansible.builtin.replace:
        path: /etc/fstab
        regexp: '^([^#].*\sswap\s.*)$'                 #Find an uncommented line that contains swap.
        replace: '# \1'                                # Put # in front of the line we matched.


    - name: set SELinux to permissive immediately
      ansible.builtin.command:
        cmd: setenforce 0
      when:
        - ansible_selinux.status == "enabled"
        - ansible_selinux.mode == "enforcing"


    - name: set SELinux to permissive permanently
      ansible.builtin.lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUX='
        line: 'SELINUX=permissive'

    - name: load overlay and br_netfilter kernel modules       # troubleshooting: not in the actual assignment but prerequisite for sysctl tasks
      ansible.builtin.command:
        cmd: "modprobe {{ item }}"
      changed_when: false                                      # modprobe is idempotent; loading an already-loaded module is a no-op
      loop:
        - overlay
        - br_netfilter

    - name: load kernel modules on boot
      ansible.builtin.copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          overlay
          br_netfilter
        mode: '0644'
    
    - name: configure Kubernetes sysctl parameters
      ansible.builtin.copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.bridge.bridge-nf-call-iptables = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward = 1
        mode: '0644'

    - name: apply sysctl parameters
      ansible.builtin.command:
        cmd: sysctl --system

